damage:
   wolf:
      - block_explostion
      - contact
      - dragon_breath
      - drowning
      - entity
      - entity_explosion
      - entity_sweep_attack
      - fire
      - fall
      - falling_block
      - lava
      - hot_floor
      #- projectile now disabled

color:
  BLACK: "&0"
  BLUE: "&1"
  BROWN: "&6"
  CYAN: "&3"
  GRAY: "&8"
  GREEN: "&a"
  LIGHT_BLUE: "&b"
  LIGHT_GRAY: "&7"
  LIME: "&a"
  MAGENTA: "&5"
  ORANGE: "&6"
  PINK: "&d"
  PURPLE: "&5"
  RED: "&4"
  WHITE: "&f"
  YELLOW: "&e"